### ISSUE TITLE
struct accessors always return ●

### ISSUE THREAD

**Issue by bennn** [philnguyen/soft-contract#105]
I expected these 2 programs to verify. I think they fail because SCV thinks a struct accessor can return anything.

#### Program 1

Defines a struct, provides an accessor, does not provide the constructor

```
#lang racket

(struct foo (x))

(provide (contract-out (foo-x (-> foo? integer?))))

;(blame
; (line 5 col 30)
; (violator
;  :
;  "/..../struct-access-0.rkt")
; (contract
;  from
;  :
;  "/..../struct-access-0.rkt")
; (contracts : integer?)
; (values : ●))
```

#### Program 2

Has two modules. One defines a struct & exports it with a contract. The other tries to use the struct.

```
#lang racket
;; struct-access-1.rkt

(struct foo (x))

(provide (contract-out (struct foo ((x exact-integer?)))))
```

```
#lang racket
;; struct-access-2.rkt

(require "struct-access-1.rkt")

(define (getx f)
  (foo-x f))

(provide (contract-out (getx (-> foo? exact-integer?))))
```

Error message from `raco scv struct-access-2.rkt`:
```
- dependency: /..../struct-access-1.rkt for `idY7`
(blame
 (line 5 col 31)
 (violator
  :
  "/..../struct-access-2.rkt")
 (contract
  from
  :
  "/..../struct-access-1.rkt")
 (contracts : exact-integer?)
 (values : ●))
```

**Comment by philnguyen** [comment]
This is a current limitation of SCV. It doesn't know that certain structs have their instances created in a controlled way. Predicate `foo?` is just a tag check. We can for now get around this by using `(struct/c foo integer?)` instead of `foo?`.

Program 1 can go through by:
```racket
#lang racket

(struct foo (x))
(define foo/c (struct/c foo integer?))

(provide (contract-out (foo-x (-> foo/c integer?))))
```

Program 2 can be fixed/hacked in the same way, although I noticed a different problem. SCV somehow thinks  struct `foo` may not have been defined in the second module, which I'll fix soon.
